### ISSUE TITLE
Remove not working in CLI

### ISSUE THREAD

**Issue by KCreate** [substack/norcal#2]
Am I missing something, or does the rm command actually not work with the event index?
I figured out that by doing a query, then passing the key to rm, works. However this is very unintuitive in my opinion.

Might be a good idea to be able to remove events by their index (The number that appears next to the title)

Any thoughts?
![screenshot 2016-06-20 at 20 29 16](https://cloud.githubusercontent.com/assets/1352680/16205771/ab04b77c-3725-11e6-9a46-1453d35bf79d.jpg)

**Comment by noffle** [comment]
Fixed in https://github.com/substack/norcal/pull/4.
