### ISSUE TITLE
pump not found

### ISSUE THREAD

**Issue by denjello** [substack/norcal#7]
i resolved this with `npm install -g pump` but there's probably a more elegant way...

**Comment by noffle** [comment]
This should be pulled in automatically by hyperlog. How did you install? What error messages did you see?

**Comment by denjello** [comment]
I installed with `npm install -g norcal`

It threw no errors while npm'ing, but complained that it couldn't find pump when I ran `norcal`.

**Comment by noffle** [comment]
@denjello Good catch! I managed to reproduce: https://github.com/substack/hyperkv/pull/7

**Comment by noffle** [comment]
I pushed 2.0.1 of `hyperkv`, however norcal still depends on < 2.0.0 of hyperkv. This will need to be upgraded + fixed before you'll see the fix.

**Comment by noffle** [comment]
Published norcal@3.1.1; all should be well now.
